export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const Create_USER_REQUEST = 'Create_USER_REQUEST';
export const Create_USER_SUCCESS = 'Create_USER_SUCCESS';
export const Create_USER_FAIL = 'Create_USER_FAIL';

// export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAIL = 'LOGIN_REQUEST_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

// Update password
export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_REQUEST_SUCCESS =
  'UPDATE_PASSWORD_REQUEST_SUCCESS';
export const UPDATE_PASSWORD_REQUEST_FAIL = 'UPDATE_PASSWORD_REQUEST_FAIL';

//
export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';
export const GET_ALL_USERS_REQUEST_SUCCESS = 'GET_ALL_USERS_REQUEST_SUCCESS';
export const GET_ALL_USERS_REQUEST_FAIL = 'GET_ALL_USERS_REQUEST_FAIL';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_REQUEST_SUCCESS = 'DELETE_USER_REQUEST_SUCCESS';
export const DELETE_USER_REQUEST_FAIL = 'DELETE_USER_REQUEST_FAIL';
